### ISSUE TITLE
it says to follow along in the console.  What console?

### ISSUE THREAD

**Issue by ThelastEconPoet** [learn-co-curriculum/js-node-practice-lab#11]
In the intro to functions lesson there are many times when it says to follow along in the console, yet the ability to open the IDE console is not given.  What console are they talking about?  Why arent instructions clearer if there is some sort of console to follow along with.  I was not told to inspect any object such that I would bring up the dev console, and again, the IDE is not available in this lesson.  Please advise, and clean up the lesson.

**Comment by maxwellbenton** [comment]
Hi @ThelastEconPoet, 

Thank you for opening this issue and providing feedback. We've recently updated this lab and confirmed that the Open IDE button now appears and is forking down and opening with the expected files.

We apologize for any frustration this may have caused, but we appreciate you taking the time to let us know of your experience so we can improve our content for future students.

Thank you!
