### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ThelastEconPoet** [learn-co-curriculum/js-node-practice-lab#12]
I am in the intro to functions lab. I opened IDE and there is only a readme file, even though it is asking me to open up the index.js and test/root.js. Neither exist. Please advise

**Comment by maxwellbenton** [comment]
Hi @ThelastEconPoet, 

Thank you for opening this issue and providing feedback. We've recently updated this lab and confirmed that the Open IDE button now appears and is forking down and opening with the expected files.

We apologize for any frustration this may have caused, but we appreciate you taking the time to let us know of your experience so we can improve our content for future students.

Thank you!
