### ISSUE TITLE
IDE problem 

### ISSUE THREAD

**Issue by brindab50** [learn-co-curriculum/js-node-practice-lab#13]
hi I'm having problems with my ide. I don't know if it's just me, but my terminal always gives me an error message. The lab I'm currently in (node practice) the IDE has no files, and the lab is saying that it does. please help me! I'm not getting any responses from anybody.

**Comment by maxwellbenton** [comment]
Hi @brindab50, 

Thank you for opening this issue and sorry to hear you were having difficulty. We've recently updated this lab and confirmed that the Open IDE button now appears and is forking down and opening with the expected files.

We apologize for any frustration this may have caused, but we appreciate you taking the time to let us know of your experience so we can improve our content for future students.

Thank you!
