### ISSUE TITLE
Missing IDE button

### ISSUE THREAD

**Issue by pwilfong01** [learn-co-curriculum/js-node-practice-lab#14]
The 'Open' IDE button is missing when I start the Node Practice lesson, but is still available if I go back to previous comleted lesson.

**Comment by maxwellbenton** [comment]
Hi @pwilfong01, 

Thank you for opening this issue and providing feedback. We've recently updated this lab and confirmed that the Open IDE button now appears and is forking down and opening as expected.

We apologize for any frustration this may have caused, but we appreciate you taking the time to let us know of your experience so we can improve our content for future students.

Thank you!
