### ISSUE TITLE
Lab References OPEN IDE but there is No IDE Button

### ISSUE THREAD

**Issue by FreeBreadsticks** [learn-co-curriculum/js-node-practice-lab#15]
Is this lab supposed to reference the IDE or no?

**Comment by phajib** [comment]
Had this same problem today. Cannot submit in order to turn lights green even though this isn't a lab.

**Comment by d-d-d-dalia** [comment]
Same problem with a student today - no IDE button though the lab references it.

**Comment by jyang81** [comment]
still no open button...

**Comment by fcorreia3** [comment]
I am experiencing the same problem. And it says "This lab is very important"!!

**Comment by andrewmc36** [comment]
same problem  No IDE on Nodes

**Comment by maxwellbenton** [comment]
Hi @FreeBreadsticks, 

Thank you for opening this issue and providing feedback. We've recently updated this lab and confirmed that the Open IDE button now appears and is forking down and opening as expected.

We apologize for any frustration this may have caused, but we appreciate you taking the time to let us know of your experience so we can improve our content for future students.

Thank you!
