### ISSUE TITLE
ANOTHER LESSON PLAN 

### ISSUE THREAD

**Issue by JayGalvan90** [learn-co-curriculum/js-node-practice-lab#16]

**Comment by maxwellbenton** [comment]
Hi @MassiveXeffectN9,

Thank you for opening this issue. Unfortunately, I am unable to identify what issue you are referring to in this issue. We've recently updated this lab to ensure it is working properly.

I am going to close this issue, but if you would like to reopen and provide further information regarding your issue, I would be happy to take another look.

Thank you!
