### ISSUE TITLE
Open IDE button not available

### ISSUE THREAD

**Issue by alexkapone** [learn-co-curriculum/js-node-practice-lab#17]
This is the second lesson so far this has happened in. I had to skip the last one but it wasn't an important lesson. This one seems more important.

**Comment by RyanBliss326** [comment]
> This is the second lesson so far this has happened in. I had to skip the last one but it wasn't an important lesson. This one seems more important.

Same with me. I get the Sandbox option instead of Open IDE

**Comment by nmalayev** [comment]
Same here. I think it's because this is the Bootcamp Prep v2 course. If you click on Curriculum in the top left and "Switch Materials" to the original Bootcamp Prep, the lessons function correctly.

**Comment by maxwellbenton** [comment]
Hi @alexkapone, 

Thank you for opening this issue and providing feedback. We've recently updated this lab and confirmed that the Open IDE button now appears and is forking down and opening as expected.

We apologize for any frustration this may have caused, but we appreciate you taking the time to let us know of your experience so we can improve our content for future students.

Thank you!
