### ISSUE TITLE
Node JS practice IDE problem 

### ISSUE THREAD

**Issue by NahomX** [learn-co-curriculum/js-node-practice-lab#19]
The instructions and the code in the IDE doesnt match.

**Comment by maxwellbenton** [comment]
Hi @NahomX, 

Thank you for opening this issue and providing feedback. We've recently updated this lab and confirmed the content in the instructions is now correctly aligned with what appears in the IDE.

We apologize for any frustration this may have caused, but we appreciate you taking the time to let us know of your experience so we can improve our content for future students.

Thank you!
