### ISSUE TITLE
Node practice not working.

### ISSUE THREAD

**Issue by pahoffart25** [learn-co-curriculum/js-node-practice-lab#20]
whenever I open the IDE on node practice it tells me that it can not find a file by that name and doesn't allow me  to work on that lesson.

**Comment by maxwellbenton** [comment]
Hi @pahoffart25,

Thank you for opening this issue and providing feedback. We've recently updated this lab and confirmed that it is now forking down and opening as expected.

We apologize for any frustration this may have caused, but we appreciate you taking the time to let us know of your experience so we can improve our content for future students.

Thank you!
