### ISSUE TITLE
Incorrect Curriculum Ordering

### ISSUE THREAD

**Issue by Tokuhisa1** [learn-co-curriculum/js-node-practice-lab#5]
The ordering of pages in this module can be confusing for new users. This page should be preceded by "From DOM To Node and the IDE" (https://learn.co/tracks/bootcamp-prep/javascript-fundamentals/programming-js-in-the-ide/from-dom-to-node-and-the-ide), and followed by "Conditional Statements" (https://learn.co/tracks/bootcamp-prep/javascript-fundamentals/programming-js-in-the-ide/conditional-statements) and "Practicing Conditional Statements" (https://learn.co/tracks/bootcamp-prep/javascript-fundamentals/programming-js-in-the-ide/practicing-conditional-statements).

**Comment by jmburges** [comment]
good catch @Tokuhisa1 looks like someone accidentally reordered things. Fixed :)
